### ISSUE TITLE
Trying to use HTTP Basic Authentication

### ISSUE THREAD

**Issue by chadwtaylor** [whichdigital/active-rest-client#40]
Followed the ReadMe to set up the credentials (username and password). It doesn't recognize username nor password. Any advice is greatly appreciated:

```
class Person < ActiveRestClient::Base
  username 'api'
  password 'eb693ec-8252c-d6301-02fd0-d0fb7-c3485'

  # ...
end
```

**Comment by andyjeffries** [comment]
This has been fixed in ce44612.
