### ISSUE TITLE
response headers?

### ISSUE THREAD

**Issue by bbrealnex** [whichdigital/active-rest-client#65]
I need to access the response headers . . . for example when I do Model.all, ResultIterator contains the status and of course the resulting objects, but I can't figure out how to get the response headers. Specifically I need the Link response header so I can do previous, next, first, last, etc.

I guess what I really need is the raw result back and not just ResultIterator.

Anyway is this possible with active-rest-client?

Sorry if I'm missing something obvious.

Thanks!

Ben

**Comment by andyjeffries** [comment]
It wasn't in there, but I understand your need (sorry for the delay in responding - I haven't been using ARC since leaving Which, but now I am).  I've just made a change to support this, so if you use 36a875b or above from this git repo, it'll expose `@your_object._headers`.
