### ISSUE TITLE
ActiveRestClient respond to 204 No Content

### ISSUE THREAD

**Issue by davidtolsma** [whichdigital/active-rest-client#66]
I have a before_request for all ActiveRestClient calls, but the server is responding with a 204 No Content on some actions. This causes an error: MultiJson::LoadError in FilesController#update 795: unexpected token at ''

before_request do |name, request| request.headers["Accept"] = 'application/json' request.headers["Content-Type"] = 'application/json' end

How can I accept some responses to be no content when using ActiveRestClient?

Also posted on SO
https://stackoverflow.com/questions/27573656/activerestclient-respond-to-204-no-content

**Comment by andyjeffries** [comment]
I've merged the pull request, but I won't be upping the version and releasing - that's really outside my area of comfort (given that I'm no longer with Which? Digital).
