### ISSUE TITLE
Send hash to JSON API

### ISSUE THREAD

**Issue by tiagotex** [whichdigital/active-rest-client#79]
ActiveRestClient is correctly configured in the rails app. I can find a contact, but when I'm trying to `update` no body is sent. I couldn't find out why, but trying using POST for debugging.

```
# model contact
class Contact < ActiveRestClient::Base
  request_body_type :json
  verbose true

  get :find, "/contacts/:id"
  post :save, "/contacts/post/:id"
end
```

```
#controler contact
def update
    if Contact.save(id: params["id"], contact: params["contact"])
   (...)
end
```

I'm trying to send an Hash (params["contact"]) to the API:
`{"contact" => {"contact_info" => {"name" => "sdfgsdfg"}}}`

When I try to send it using the CURL via terminal the params received in the API are:
`{"contact"=>{"contact_info"=>{"name"=>"Philipp123"}}, "splat"=>[], "captures"=>["54dd076c3465300003380000"], "id"=>"54dd076c3465300003380000"}`

When I do it in the rails app I receive:
`{"{\"contact\":{\"contact_info\":{\"name\":\"sdfgsdfg\"}}}"=>nil, "splat"=>[], "captures"=>["54dd076c3465300003380000"], "id"=>"54dd076c3465300003380000"}`

What am I doing wrong? How do I send an hash?

**Comment by andyjeffries** [comment]
I just tried writing an RSpec test that fails for this and it passed.  Out of interest, what happens if you try using:

```ruby
Contact.save(id: params["id"], contact: params["contact"].to_hash)
```

**Comment by andyjeffries** [comment]
I just tried testing this with a small app too and it works...

```ruby
class People < ActiveRestClient::Base
  request_body_type :json
  verbose true

  base_url "http://requestb.in"

  post :create, "/1j27af11"
end
```

```ruby
class PagesController < ApplicationController
  def create
    People.create(contact: params[:contact])
  end
```

**Comment by tiagotex** [comment]
I found the solution, after reading the rest-client-client codebase and carefully analyzing the logs from sending and receiving apps. My API is a JSON API, `content_type` is defined as `'application/json'`.

So the solution was to add and header in the model:

```
class Contact < ActiveRestClient::Base
  request_body_type :json
  before_request :add_json_header

  post :save, "/contacts//:id"

  def add_json_header(name, request)
    if name == :save
      request.headers = {"Content-Type" => "application/json"}
    end
  end
end
```

This was very obscure. My understanding is that when we define `request_body_type :json` the header `{"Content-Type" => "application/json"}` should be automatically added. This should be the default.

Other solutions could be creating `request_content_type` to easily set it.

Also this should be a behavior well documented, which is not the case, to avoid pain to other developers.

I'm available to implement any of the changes I suggested. @andyjeffries What's your opinion?

**Comment by andyjeffries** [comment]
I'd like the "automatically added" option.  I think that's most logical :-)  Also, if you don't use `request_body_type :json` then it should set the form-encoded content-type (while you're in that area).

I'll merge the pull request quickly when done :-)
