### ISSUE TITLE
Multiple clients for different APIs

### ISSUE THREAD

**Issue by bilby91** [whichdigital/active-rest-client#97]
Is it possible to have multiple clients that use different APIs with different credentials ? I'm concerned about this because all the configuration are stored in class variables in `ActiveRestClient::Base`.

Thanks!

**Comment by andyjeffries** [comment]
They're stored in class instance variables (@variable within a class method).  So you can do this and indeed the username/password is intended to be called within the specific API class, not a parent class.  For example, this works fine with both classes using different API credentials (obviously if you had more than one class using a given username/password I would definitely extract it to a constant):

```ruby
# API Endpoint defined at https://httpbin.org/

class Person < ActiveRestClient::Base
  base_url "https://httpbin.org/basic-auth"
  username "user"
  password "passwd"
  
  get :all, "/user/passwd"
end

class Car < ActiveRestClient::Base
  base_url "https://httpbin.org/basic-auth"
  username "someone"
  password "else"
  
  get :all, "/someone/else"
end

Person.all
Car.all
```
